const presentes = [
  { id: 1, categoria: "Banho / Têxtil", nome: "Jogo de Banheiro Pineapple 3 Peças", valorVista: 159.81, valorParcelado: null, imagem: "images/gift-cama-mesa-banho-01.webp" },
  { id: 2, categoria: "Banho / Têxtil", nome: "Jogo de Colcha Casal Maite 3 Peças Buddemeyer", valorVista: 422.56, valorParcelado: 140.85, imagem: "images/gift-cama-mesa-banho-02.webp" },
  { id: 3, categoria: "Banho / Têxtil", nome: "Jogo de Edredom Queen Max 3 Peças", valorVista: 679.58, valorParcelado: 226.53, imagem: "images/gift-cama-mesa-banho-03.webp" },
  { id: 4, categoria: "Banho / Têxtil", nome: "Jogo de Lençol Casal New Soft 4 peças - Home Style", valorVista: 216.23, valorParcelado: null, imagem: "images/gift-cama-mesa-banho-04.webp" },
  { id: 5, categoria: "Banho / Têxtil", nome: "Jogo de Lençol Super King Damask Stripes", valorVista: 861.38, valorParcelado: 287.13, imagem: "images/gift-cama-mesa-banho-05.webp" },
  { id: 6, categoria: "Banho / Têxtil", nome: "Jogos de Toalhas de Banho Fofinhas", valorVista: 156.60, valorParcelado: null, imagem: "images/gift-cama-mesa-banho-06.webp" },
  { id: 7, categoria: "Cozinha", nome: "Aparelho de Jantar Polka Dots 20 Peças", valorVista: 478.98, valorParcelado: 159.66, imagem: null },
  { id: 8, categoria: "Cozinha", nome: "Assadeira Retangular Alumínio Ecolon 43x21 cm", valorVista: 358.62, valorParcelado: 119.54, imagem: null },
  { id: 9, categoria: "Cozinha", nome: "Chaleira Elétrica para os noivos ganharem tempo na cozinha", valorVista: 229.13, valorParcelado: null, imagem: null },
  { id: 10, categoria: "Cozinha", nome: "Escorredor de Louças Inox Madri Cromado", valorVista: 371.15, valorParcelado: 123.72, imagem: null },
  { id: 11, categoria: "Cozinha", nome: "Faqueiro Bellagio 24 peças - Brinox", valorVista: 188.65, valorParcelado: null, imagem: null },
  { id: 12, categoria: "Cozinha", nome: "Faqueiro Berna 30 Peças", valorVista: 974.22, valorParcelado: 324.74, imagem: null },
  { id: 13, categoria: "Cozinha", nome: "Faqueiro Prata Pisa 130 Peças", valorVista: 5299.68, valorParcelado: 1766.56, imagem: null },
  { id: 14, categoria: "Cozinha", nome: "Jogo de Panelas Quadro 5 Peças", valorVista: 1914.53, valorParcelado: 638.18, imagem: null },
  { id: 15, categoria: "Cozinha", nome: "Jogo de Panelas Smart 5 Peças", valorVista: 471.46, valorParcelado: 157.15, imagem: null },
  { id: 16, categoria: "Cozinha", nome: "Jogo de Panelas Vermont 5 Peças", valorVista: 598.09, valorParcelado: 199.36, imagem: null },
  { id: 17, categoria: "Cozinha", nome: "Jogo de Porta-Condimentos com Suporte Rack 6 Peças", valorVista: 159.81, valorParcelado: null, imagem: null },
  { id: 18, categoria: "Cozinha", nome: "Jogo de Prato Raso Legacy 6 Peças - Germer", valorVista: 208.71, valorParcelado: null, imagem: null },
  { id: 19, categoria: "Cozinha", nome: "Jogo de Taça de Vinho Salute 710ml 4 Peças", valorVista: 247.58, valorParcelado: null, imagem: null },
  { id: 20, categoria: "Cozinha", nome: "Jogo de Taças de Vinho para esse casal que ama um vinho", valorVista: 125.52, valorParcelado: null, imagem: null },
  { id: 21, categoria: "Cozinha", nome: "Jogo Massa Mangiare 5 Peças Schimidt", valorVista: 233.78, valorParcelado: null, imagem: null },
  { id: 22, categoria: "Cozinha", nome: "Moedor de Pimenta (esse o noivo PRECISA ter)", valorVista: 73.71, valorParcelado: null, imagem: null },
  { id: 23, categoria: "Cozinha", nome: "Panela de Pressão Vapt 4,5 Litros - Brinox", valorVista: 387.46, valorParcelado: 129.15, imagem: null },
  { id: 24, categoria: "Cozinha", nome: "Panela para Caldos com Concha Preta Pamplona", valorVista: 260.11, valorParcelado: null, imagem: null },
  { id: 25, categoria: "Cozinha", nome: "Pipoqueira Elétrica Pop Movie 1200W 127V - Cadence", valorVista: 184.89, valorParcelado: null, imagem: null },
  { id: 26, categoria: "Cozinha", nome: "Tábua BBQ para o noivo provar sua hombridade", valorVista: 187.69, valorParcelado: null, imagem: null },
  { id: 27, categoria: "Decoração", nome: "Porta Retrato: esse vai a foto do nosso casal preferido", valorVista: 58.17, valorParcelado: null, imagem: "images/gift-decoracao-01.webp" },
  { id: 28, categoria: "Decoração", nome: "Vaso Murano Fluid 36 cm x 29 cm - Cristais", valorVista: 1538.41, valorParcelado: 512.80, imagem: "images/gift-decoracao-02.webp" },
  { id: 29, categoria: "Decoração", nome: "Vaso Murano Treviso 25 cm - Cristais Cá d'Oro", valorVista: 1223.71, valorParcelado: 407.90, imagem: "images/gift-decoracao-03.webp" },
  { id: 30, categoria: "Eletrodomésticos", nome: "Adega 28 Garrafas Termo", valorVista: 2414.78, valorParcelado: 804.93, imagem: "images/gift-eletrodomesticos-01.webp" },
  { id: 31, categoria: "Eletrodomésticos", nome: "Adega 33 Garrafas Compressor", valorVista: 4284.13, valorParcelado: 1428.04, imagem: "images/gift-eletrodomesticos-02.webp" },
  { id: 32, categoria: "Eletrodomésticos", nome: "Forno Elétrico 10 Litros Compact 127V - Oster", valorVista: 408.77, valorParcelado: 136.26, imagem: "images/gift-eletrodomesticos-03.webp" },
  { id: 33, categoria: "Eletrodomésticos", nome: "Forno Ofor300 30 Litros", valorVista: 848.84, valorParcelado: 282.95, imagem: "images/gift-eletrodomesticos-04.webp" },
  { id: 34, categoria: "Eletroportáteis", nome: "Aspirador de Pó Ciclônico 2 em 1 Vertical 1200W", valorVista: 322.80, valorParcelado: 107.60, imagem: null },
  { id: 35, categoria: "Eletroportáteis", nome: "Aspirador Robô Keep Clean", valorVista: 1851.85, valorParcelado: 617.28, imagem: null },
  { id: 36, categoria: "Eletroportáteis", nome: "Batedeira Planetária Bowl 750W", valorVista: 654.51, valorParcelado: 218.17, imagem: null },
  { id: 37, categoria: "Eletroportáteis", nome: "Batedeira Stand Mixer Bowl Inox", valorVista: 3168.29, valorParcelado: 1056.10, imagem: null },
  { id: 38, categoria: "Eletroportáteis", nome: "Cafeteira Citiz 1260W", valorVista: 898.99, valorParcelado: 299.66, imagem: null },
  { id: 39, categoria: "Eletroportáteis", nome: "Cafeteira Expresso Modo S04", valorVista: 611.88, valorParcelado: 203.96, imagem: null },
  { id: 40, categoria: "Eletroportáteis", nome: "Espremedor de Frutas Chrome 500ml Automático", valorVista: 285.19, valorParcelado: null, imagem: null },
  { id: 41, categoria: "Eletroportáteis", nome: "Ferro para a noiva deixar tudo bem passadinho", valorVista: 146.24, valorParcelado: null, imagem: null },
  { id: 42, categoria: "Eletroportáteis", nome: "Fritadeira 5 Litros 1400W", valorVista: 733.87, valorParcelado: 244.62, imagem: null },
  { id: 43, categoria: "Eletroportáteis", nome: "Grill Elétrico Clássica 1200W", valorVista: 509.07, valorParcelado: 169.69, imagem: null },
  { id: 44, categoria: "Eletroportáteis", nome: "Jogo Para Churrasco Polywood Inox 3 Peças", valorVista: 159.81, valorParcelado: null, imagem: null },
  { id: 45, categoria: "Eletroportáteis", nome: "Liquidificador Expressionist 900W", valorVista: 1059.47, valorParcelado: 353.16, imagem: null },
  { id: 46, categoria: "Eletroportáteis", nome: "Liquidificador Super Chef 750W", valorVista: 260.11, valorParcelado: null, imagem: null },
  { id: 47, categoria: "Eletroportáteis", nome: "Liquidificador Versatile 450W", valorVista: 540.42, valorParcelado: 180.14, imagem: null },
  { id: 48, categoria: "Eletroportáteis", nome: "Multiprocessador Chrome 7 Peças", valorVista: 547.94, valorParcelado: 182.65, imagem: null },
  { id: 49, categoria: "Eletroportáteis", nome: "Panela Elétrica Chef 630W", valorVista: 441.37, valorParcelado: 147.12, imagem: null },
  { id: 50, categoria: "Eletroportáteis", nome: "Panela Elétrica Multiuso Gran Taste 1,8L 700W", valorVista: 347.34, valorParcelado: 115.78, imagem: null },
  { id: 51, categoria: "Eletroportáteis", nome: "Panela Elétrica para Fondue Delight", valorVista: 314.33, valorParcelado: 104.78, imagem: null },
  { id: 52, categoria: "Eletroportáteis", nome: "Torradeira Easyline 800W 127V - Electrolux", valorVista: 209.96, valorParcelado: null, imagem: null },
  { id: 53, categoria: "Eletroportáteis", nome: "Vaso Murano Gout 35 cm", valorVista: 1726.47, valorParcelado: 575.49, imagem: null },
  { id: 54, categoria: "Utilidades Domésticas", nome: "Cesto de Roupa Trama com Tampa e Rodízios", valorVista: 428.83, valorParcelado: 142.94, imagem: null },
  { id: 55, categoria: "Utilidades Domésticas", nome: "MOP Giratório Ciclone 12L - Flash Limp", valorVista: 315.86, valorParcelado: 105.29, imagem: null },
];
